name: kidou_fl
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.10.0

dependencies:
  flutter:
    sdk: flutter

  # model
  flutter_riverpod: ^3.0.3
  riverpod_annotation: ^3.0.3
  freezed_annotation: ^3.1.0
  json_annotation: ^4.9.0

  go_router: ^17.0.0
  toastification: ^3.0.3

  #  audio
  record: ^6.1.2
  permission_handler: ^12.0.1
  
  # logging
  talker: ^5.0.2

  #  web
  web_socket_channel: ^3.0.3
  http: ^1.5.0

  cupertino_icons: ^1.0.8

# dependency_overrides:
#   test_api: 0.7.7

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.10.3
  freezed: ^3.1.0
  json_serializable: ^6.9.5
  riverpod_generator: ^3.0.3
  riverpod_lint: ^3.0.3

  custom_lint: ^0.8.1
  flutter_lints: ^6.0.0

  flutter_launcher_icons: ^0.14.4


# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/config/

